[build-system]
requires = [
    "setuptools>=83.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "robotframework-nl"
version = "4.0.0"
description = "RobotNL is a proving ground to boost Robot Framework closer to Natural Language."
readme = "README.md"
authors = [{ name = "Johan Foederer", email = "github@famfoe.nl" }]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["robotframework", "robot", "testing", "dsl"]
dependencies = [
    "robotframework >= 7.0",
]
requires-python = ">=3.14"

[tool.setuptools]
packages = ["robotnl"]

[project.urls]
Homepage = "https://github.com/JFoederer/robotframeworkNL"
